// <auto-generated />
namespace _2015147458_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Model_1A : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_1A));
        
        string IMigrationMetadata.Id
        {
            get { return "201706110259460_Model_1A"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
